# Copyright (c) 2019-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the LICENSE file.

# Configuration for golangci-lint.
# See https://golangci-lint.run/usage/configuration for more details.

issues:
  # Prevent linter rules/issues, that are explicitly enabled by this configuration, to be ignored due to golangci-lint's
  # set of issues that are ignored by default.
  exclude-use-default: false
  exclude-rules:
    # Prevent issues on `go generate` command directive lines.
    - linters:
        - lll
      source: "^//go:generate "
    # Allow URLs with any length.
    - linters:
        - lll
      source: (https?):\/\/[^\s\/$.?#].[^\s]*
    # Exclude some linters from running on test files.
    - path: _test\.go
      linters:
        - gocyclo
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - bidichk
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilnil
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck
  # Run all linters, not only fast ones.
  fast: false

# Configurations for enabled linters.
# See https://golangci-lint.run/usage/linters for more details.
linters-settings:
  depguard:
    list-type: blacklist
    # Do not check against the standard library.
    include-go-root: false
    packages:
      - golang.org/x/net/context
    packages-with-error-message:
      - golang.org/x/net/context: "As of Go 1.7 this package is available in the standard library under the name context: golang.org/pkg/context"

  dupl:
    # Minimum count of tokens before triggering as duplicate code.
    threshold: 100

  errcheck:
    # Report about not checking of errors in type assertions.
    # Example: `a := b.(CustomStruct)`
    check-type-assertions: true

  errorlint:
    # Prevent false-positive matches for code lines that explicitly do not wrap the error to prevent it become part of
    # the public API.
    # See https://github.com/svengreb/tmpl-go/issues/39 and https://github.com/svengreb/tmpl-go/issues/64 for details.
    errorf: false

  gci:
    # A comma-separated list of prefixes for local package imports to be put after 3rd-party packages.
    local-prefixes: github.com/svengreb/wand

  goconst:
    min-len: 2
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  gofumpt:
    extra-rules: true
    lang-version: "1.17"

  goheader:
    values:
      const:
        AUTHOR: Sven Greb
        YEAR: 2019-present
      regexp:
        EMAIL: .*@svengreb\.de
    template: |-
      Copyright (c) {{ YEAR }} {{ AUTHOR }} <{{ EMAIL }}>
      This source code is licensed under the MIT license found in the LICENSE file.

  goimports:
    # A comma-separated list of prefixes for local package imports to be put after 3rd-party packages.
    local-prefixes: github.com/svengreb/wand

  gomnd:
    settings:
      mnd:
        # The list of enabled checks.
        # See https://github.com/tommy-muehle/go-mnd/#checks for more details.
        checks: argument,assign,case,condition,operation,return

  govet:
    check-shadowing: true

  importas:
    execSupport: github.com/svengreb/wand/internal/support/exec
    osSupport: github.com/svengreb/wand/internal/support/os

  lll:
    line-length: 160
    tab-width: 2

  misspell:
    locale: US
    ignore-words:
      - inkpen
      - magefile
      - nib

  # See https://github.com/mgechev/revive#available-rules and
  # https://github.com/mgechev/revive#recommended-configuration for more details.
  revive:
    ignore-generated-header: false
    severity: warning
    error-code: 1
    # Ignore linting errors with less than 0.2 confidence.
    confidence: 0.2
    rules:
      - name: atomic
      - name: context-as-argument
      - name: deep-exit
      - name: defer
      - name: duplicated-imports
        severity: error
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
        severity: error
      - name: error-strings
      - name: errorf
      - name: exported
        arguments:
          - checkPrivateReceivers
          - disableStutteringCheck
      - name: identical-branches
      - name: if-return
      - name: import-shadowing
        severity: error
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
        severity: error
      - name: string-of-int
        severity: error
      - name: superfluous-else
      - name: time-naming
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
      - name: unreachable-code
      - name: useless-break
      - name: var-declaration

  tagliatelle:
    case:
      use-field-name: true
      rules:
        bson: goCamel
        json: goCamel
        mapstructure: snake
        xml: goCamel
        yaml: goCamel

  wrapcheck:
    ignorePackageGlobs:
      - github.com/svengreb/wand/*

# Options for analysis runs.
run:
  deadline: 15m

service:
  golangci-lint-version: 1.43.x
